insert into users (email, fname, lname, password, isadmin) values ('johndoe', 'John' ,'Doe', 'admin', true);
insert into users (email, fname, lname, password) values ('eottiwill0@google.com.hk', 'Edsel' ,'Ottiwill', 'YdW3g3Ye');
insert into users (email, fname, lname, password) values ('vdracey1@usnews.com', 'Vanessa' ,'Dracey', 'ne8LIdSMK');
insert into users (email, fname, lname, password) values ('rkira2@prlog.org', 'Raddy' ,'Kira', 'jAdH8T45d');
insert into users (email, fname, lname, password) values ('twallhead3@si.edu', 'Traver' ,'Wallhead', 'AfpLQqpyZmfT');
insert into users (email, fname, lname, password) values ('vvonasek4@rediff.com', 'Vite' ,'Vonasek', 'BjgaO4um1oXo');
insert into users (email, fname, lname, password) values ('mfaragan5@pbs.org', 'Marita' ,'Faragan', 'IQRRNWnpAf');
insert into users (email, fname, lname, password) values ('aberens6@artisteer.com', 'Athena' ,'Berens', 'e0cgM4o1oce');
insert into users (email, fname, lname, password) values ('clucks7@squidoo.com', 'Chrysler' ,'Lucks', 'nZF7VN1H6FR');
insert into users (email, fname, lname, password) values ('afrearson8@drupal.org', 'Arman' ,'Frearson', 'bJpw8nP');
insert into users (email, fname, lname, password) values ('tbuckthought9@i2i.jp', 'Theresita' ,'Buckthought', 'ze40MxN7');
insert into users (email, fname, lname, password) values ('lis@douglascollege.ca', 'Simon' ,'Li', '123456');
insert into users (email, fname, lname, password) values ('wongi5@douglascollege.ca', 'Ivan' ,'Wong', '654321');





insert into products (name, price, description, image) values ('Pork Loin Bine - In Frenched', 22.18, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_1.jpg');
insert into products (name, price, description, image) values ('Chips Potato Reg 43g', 12.40, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_2.jpg');
insert into products (name, price, description, image) values ('Wine - Lamancha Do Crianza', 55.49, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_3.jpg');
insert into products (name, price, description, image) values ('Roe - White Fish', 50.98, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_4.jpg');
insert into products (name, price, description, image) values ('Island Oasis - Ice Cream Mix', 96.70, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_5.jpg');
insert into products (name, price, description, image) values ('Asparagus - White, Fresh', 55.72, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_6.jpg');
insert into products (name, price, description, image) values ('Radish - Black, Winter, Organic', 42.07, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_7.jpg');
insert into products (name, price, description, image) values ('Barramundi', 2.94, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_1.jpg');
insert into products (name, price, description, image) values ('Ice Cream Bar - Hagen Daz', 13.00, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_2.jpg');
insert into products (name, price, description, image) values ('Ecolab - Hobart Upr Prewash Arm', 65.21, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_3.jpg');
insert into products (name, price, description, image) values ('Oregano - Dry, Rubbed', 91.49, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_4.jpg');
insert into products (name, price, description, image) values ('Parsnip', 10.01, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_6.jpg');
insert into products (name, price, description, image) values ('Gelatine Leaves - Bulk', 49.56, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_5.jpg');
insert into products (name, price, description, image) values ('Container - Foam Dixie 12 Oz', 37.40, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_1.jpg');
insert into products (name,  price, description, image) values ('Brandy - Bar', 75.08, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_7.jpg');
insert into products (name, price, description, image) values ('Extract Vanilla Pure', 73.89, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_6.jpg');
insert into products (name, price, description, image) values ('Bread - Dark Rye', 85.01, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_3.jpg');
insert into products (name, price, description, image) values ('Guava', 27.81, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_5.jpg');
insert into products (name, price, description, image) values ('Triple Sec - Mcguinness', 85.56, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_1.jpg');
insert into products (name, price, description, image) values ('Peach - Halves', 40.33, 'Healthy eating means eating a variety of foods that give you the nutrients you need to maintain your health, feel good, and have energy. These nutrients include protein, carbohydrates, fat, water, vitamins, and minerals.','dishes_4.jpg');





insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 1);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 2);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 3);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 4);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 5);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 6);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 7);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 8);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 9);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 10);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 11);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 12);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 13);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 14);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 15);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 16);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 2);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 2);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 1);
insert into recipes (name, description, product_id) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 1);


insert into blogs (title, content, username, email) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 'John Doe', 'johndoe');
insert into blogs (title, content, username, email) values ('Summer Squash, Mint, and Pecorino Pasta', '1. Cook pasta per package directions. Reserve ¾ cup cooking liquid, then drain.
2. Meanwhile, heat oil in large, deep skillet on medium. Cook shallot, stirring occasionally, until golden brown, 3 to 4 minutes. Add squash and ½ teaspoon each salt and pepper and cook, tossing occasionally, until squash is very tender but still holds its shape, 10 to 12 minutes.
3. Add pasta to skillet and toss with squash and cheese, adding reserved cooking liquid 2 tablespoons at a time, to form a sauce that coats pasta. Fold in mint and lemon juice. Top with additional cheese and black pepper if desired.', 'John Doe', 'johndoe');
